novelblog/core/views.py
from flask import render_template, Blueprint

core = Blueprint('core', __name__)

@core.route('/')
def home():
    return render_template('home.html')

@core.route('/about')
def about():
    return render_template('about.html')

novelblog/novels/views.py
from flask import abort
from flask import render_template, Blueprint, redirect, url_for, request
from flask_login import login_required, current_user
from novelblog import db
from novelblog.novels.forms import CommentForm, NovelForm
from novelblog.models import Comments, Novel
from novelblog.novels.picture_handler import add_novel_pic

novels = Blueprint('novels', __name__)

@novels.route('/index')
@login_required
def index():
    return render_template('index.html', novels=Novel.query.all())


@novels.route('/addnovel', methods=['GET', 'POST'])
@login_required
def addnovel():
    form = NovelForm()

    if form.validate_on_submit():
        title = form.title.data
        pic = None
        if form.picture.data:
            pic = add_novel_pic(form.picture.data, title)
        novel = Novel(title = title, genre = form.genre.data, author = form.author.data, novel_image = pic)
        db.session.add(novel)
        db.session.commit()

        return render_template('index.html', novels=Novel.query.all())
    return render_template('addnovel.html', form=form, novels=Novel.query.all())


@novels.route('/editnovel/<novelId>', methods=['GET', 'POST'])
@login_required
def editnovel(novelId):
    form = NovelForm()

    novel = Novel.query.filter_by(id = novelId).first()
    if form.validate_on_submit():
        novel.title = form.title.data
        novel.author = form.author.data
        novel.genre = form.genre.data
        pic = novel.novel_image
        if form.picture.data:
            pic = add_novel_pic(form.picture.data, novel.title)
        novel.novel_image = pic
        db.session.commit()

        return redirect(url_for('novels.index'))

    elif request.method == 'GET':
        form.title.data = novel.title
        form.author.data = novel.author
        form.genre.data = novel.genre
        form.picture.data = novel.novel_image

    return render_template('addnovel.html', form=form, novels=Novel.query.all())



@novels.route('/deletenovel/<novelId>', methods=['GET', 'POST'])
@login_required
def deletenovel(novelId):
    novel = Novel.query.filter_by(id = novelId).first()
    db.session.delete(novel)
    db.session.commit()

    return redirect(url_for('novels.index'))


@novels.route('/addfeedback/<novelId>', methods=['GET', 'POST'])
@login_required
def addfeedback(novelId):
    form = CommentForm()

    if form.validate_on_submit():
        comment = Comments(user_id = current_user.id, novel_id = novelId, user_name = current_user.username, feedback=form.feedback.data)
        db.session.add(comment)
        db.session.commit()

        return redirect(url_for('novels.addfeedback', novelId=novelId))
    return render_template('addfeedback.html', form=form, feedback=Comments.query.filter_by(novel_id = novelId).all(), count=Comments.query.filter_by(novel_id = novelId).count())


@novels.route('/deletefeedback/<novelId>/<commentId>', methods=['GET', 'POST'])
@login_required
def deletefeedback(novelId, commentId):
    form = CommentForm()
    comment = Comments.query.filter_by(id = commentId, novel_id = novelId).first()
    if comment.user_id != current_user.id:
        abort(403)
    else:
        if comment != None:
            db.session.delete(comment)
            db.session.commit()

            return redirect(url_for('novels.addfeedback', novelId=novelId))

    return render_template('addfeedback.html', form=form, comments=Comments.query.all(), count=Comments.query.count())


@novels.route('/editfeedback/<novelId>/<commentId>', methods=['GET', 'POST'])
@login_required
def editfeedback(novelId, commentId):
    form = CommentForm()
    comment = Comments.query.filter_by(id = commentId, novel_id = novelId).first()
    if comment.user_id != current_user.id:
        abort(403)
    if form.validate_on_submit():
        comment.feedback = form.feedback.data
        db.session.commit()

        return redirect(url_for('novels.addfeedback', novelId=novelId))

    elif request.method == 'GET':
        form.feedback.data = comment.feedback

    return render_template('addfeedback.html', form=form)


@novels.route('/like/<novelId>/<action>')
@login_required
def likeaction(novelId, action):
    novel = Novel.query.filter_by(id=novelId).first_or_404()
    if action == 'like':
        current_user.like_novel(novel)
        db.session.commit()
    if action == 'unlike':
        current_user.unlike_novel(novel)
        db.session.commit()
    return redirect(request.referrer)

novelblog/users/views.py
from flask import render_template, redirect, request, url_for, flash, Blueprint
from flask_login import login_user, login_required, logout_user
from novelblog import db
from novelblog.users.forms import RegistrationForm, LoginForm
from novelblog.models import User

users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()

        flash("Thanks for registering!")
        return redirect(url_for('users.login'))
        
    return render_template('register.html', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()

        if user is None:
            return render_template('login.html', form=form, message="User not found! Please register!")

        elif not user.check_password(form.password.data):
            return render_template('login.html', form=form, message="Wrong password! Please try again!")

        elif user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash("Login successful!")

            next = request.args.get('next')

            if next == None or not next[0] == '/':
                next = url_for('novels.index')

            return redirect(next)

    return render_template('login.html', form=form)

@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('core.home'))

novelblog/templates/addfeedback.html
{% extends 'base.html' %} 

    {% block content %}

        <div class="container">
            <form method="POST">
                <div class="form-group">
                    {{form.hidden_tag()}}
                </div>
                <div class="form-group">
                    {{form.feedback.label(class='form-label')}}{{form.feedback(class='form-control')}}
                </div>
                <div class="form-group">
                    {{form.submit()}}
                </div>

            </form>

            {% if feedback: %}
                <h4>Comments ({{count}})</h4>
                {% for comment in feedback %} 
                    <p class="bg-light text-dark" style="display: inline;">{{comment.feedback}} </p>
                    <p style="color:darkgray; line-height: 1px;">{{comment.user_name}}
                        {% if comment.user_name == current_user.username %}
                            <a href="{{url_for('novels.editfeedback', novelId=comment.novel_id, commentId=comment.id)}}"><i class="bi bi-pencil"></i></a>
                            &nbsp;&nbsp;
                            <a href="{{url_for('novels.deletefeedback', novelId=comment.novel_id, commentId=comment.id)}}"><i class="bi bi-trash3"></i></a>
                        {% endif %}
                    </p>
                    <hr />
                {% endfor %}
            {% endif %}

        </div>

    {% endblock %}

novelblog/templates/addnovel.html
{% extends 'base.html' %} 

    {% block content %}

        <div class="container">
            <form method="POST" enctype="multipart/form-data">
                <div class="form-group">
                    {{form.hidden_tag()}}
                </div>
                <div class="form-group">
                    {{form.title.label(class='form-label')}}
                    {{form.title(class='form-control')}}
                </div>
                <div class="form-group">
                    {{form.genre.label(class='form-label')}}
                    {{form.genre(class='form-control')}}
                </div>
                <div class="form-group">
                    {{form.author.label(class='form-label')}}
                    {{form.author(class='form-control')}}
                </div>
                <div class="form-group">
                    {{ form.picture.label(class="form-group") }}
                    {{ form.picture(class="form-control-file") }}
                  </div>
                <div class="form-group">
                    {{form.submit()}}
                </div>

            </form>

        </div>

    {% endblock %}

novelblog/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css" integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e" crossorigin="anonymous">
        <title>Novels</title>

        <style>
            button {
                color: white;
                background-color: chartreuse;
            }
            
        </style>

    </head>
    <body>
        <nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd;">
            <div class="container-fluid">
                <a class="nav-item nav-link" href="{{url_for('core.home')}}">Home</a>
            
                {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{url_for('novels.index')}}">Novels</a>
                    {% if current_user.username == 'admin' %} 
                        <a class="nav-item nav-link" href="{{url_for('novels.addnovel')}}">Add Novel</a>
                    {% endif %} 
                    <a class="nav-item nav-link" href="{{url_for('users.logout')}}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="{{url_for('users.login')}}">Login</a>
                    <a class="nav-item nav-link" href="{{url_for('users.register')}}">Register</a>
                {% endif %}
            </div>
        </nav>

        <div class="container">
            {% block content %} 
            {% endblock %}
        </div>

    </body>
</html>

novelblog/templates/home.html
{% extends 'base.html' %} 

    {% block content %}

        <div class="jumbotron">
            <h1>Welcome to the world of Novels</h1>
            <p>Dive in to find amazing novels to read! You can mark favorites and add feedbacks too!!</p>
        </div>

    {% endblock %}

novelblog/templates/index.html
{% extends 'base.html' %} 

    {% block content %}

        <div class="jumbotron">
            <h1>Welcome to the world of Novels</h1>
        </div>
            
        <div class="row">
            {% for novel in novels %} 
                <div class="col-sm-4 mt-4">
                    <div class="card border-secondary h-100" style="width: 18rem;">
                        <img src="{{novel.novel_image}}" class="card-img-top" height="350" alt="Novel Image">
                        <div class="card-body">
                            <h5 class="card-title">{{novel.title}}</h5>
                            <p class="card-text">Genre: {{novel.genre}}</p>
                            <p>Author: {{novel.author}}</p>
                            <a href="{{url_for('novels.addfeedback', novelId=novel.id)}}">Comments</a>
                            {% if current_user.has_liked_novel(novel) %} 
                                <a href="{{url_for('novels.likeaction', novelId=novel.id, action='unlike')}}"  class="btn btn-outline-danger"><i class="bi bi-heart-fill"></i></a>
                            {% else %}
                                <a href="{{url_for('novels.likeaction', novelId=novel.id, action='like')}}"  class="btn btn-outline-danger"><i class="bi bi-heart"></i></a>
                            {% endif %}
                            <br />
                            {% if current_user.username == 'admin' %} 
                                <a href="{{url_for('novels.editnovel', novelId=novel.id)}}"><i class="bi bi-pencil"></i></a>
                                &nbsp;&nbsp;
                                <a href="{{url_for('novels.deletenovel', novelId=novel.id)}}"><i class="bi bi-trash3"></i></a>
                            {% endif %} 
                        </div>
                    </div>
                </div>
            {% endfor %}           
        </div>

    {% endblock %}

novelblog/templates/login.html
{% extends 'base.html' %} 

    {% block content %}

        <div class="container">
            <form method="POST">
                <div class="form-group">
                    {{form.hidden_tag()}}
                </div>
                <div class="form-group">
                    {{form.username.label(class='form-label')}}{{form.username(class='form-control')}}
                </div>
                <div class="form-group">
                    {{form.password.label(class='form-label')}}{{form.password(class='form-control')}}
                </div>
                <div class="form-group">
                    {{form.submit()}}
                </div>

            </form>

            {% if message %} 
                <h5>{{message}}</h5>
            {% endif %}
        </div>

    {% endblock %}

novelblog/templates/register.html
{% extends 'base.html' %} 

    {% block content %}

        <div class="container">
            <form method="POST">
                <div class="form-group">
                    {{form.hidden_tag()}}
                </div>
                <div class="form-group">
                    {{form.username.label(class='form-label')}}{{form.username(class='form-control')}}
                </div>
                <div class="form-group">
                    {{form.email.label(class='form-label')}}{{form.email(class='form-control')}}
                </div>
                <div class="form-group">
                    {{form.password.label(class='form-label')}}{{form.password(class='form-control')}}
                </div>
                <div class="form-group">
                    {{form.confirm_password.label(class='form-label')}}{{form.confirm_password(class='form-control')}}
                </div>
                <div class="form-group">
                    {{form.submit()}}
                </div>
            </form>
        </div>

    {% endblock %}